"""
Django settings for LearningPortal project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#BASE_URL = 'https://getskill.herokuapp.com'
BASE_URL = 'http://127.0.0.1:8000'

DEFAULT_FREE_QUUESTION = 10
DEFAULT_FREE_QUUESTION_DURATION = 10

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nq42zuem74ehydhno0hv$4jm#rj*h7f#jbyk1o0u=miubn^o@e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'qbank',
    "sslserver",
    'django_summernote',
    'social_django',
    'django_social_share',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]


ROOT_URLCONF = 'LearningPortal.urls'

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]
# SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

WSGI_APPLICATION = 'LearningPortal.wsgi.application'

# CSRF_TRUSTED_ORIGINS=['https://explorerg.com']

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME' : 'd1clk7i12laju8',
#         'USER' : 'nacphzotpgghgi',
#         'PASSWORD' : '04ee0f6893cf82732ff2033088d8a8ba209ecf2fcf344cbdf6eb56f15dc39568',
#         'HOST' : 'ec2-54-85-56-210.compute-1.amazonaws.com',
#         'PORT' : '5432'
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME' : 'learning',
#         'USER' : 'postgres',
#         'PASSWORD' : 'admin',
#         'HOST' : 'localhost',
#         'PORT' : '5432'
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME' : 'chetan',
#         'USER' : 'postgres',
#         'PASSWORD' : 'admin',
#         'HOST' : 'localhost',
#         'PORT' : '5432'
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME' : 'new',
#         'USER' : 'postgres',
#         'PASSWORD' : 'admin',
#         'HOST' : 'localhost',
#         'PORT' : '5432'
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME' : 'db11',
        'USER' : 'postgres',
        'PASSWORD' : 'admin',
        'HOST' : 'localhost',
        'PORT' : '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(CORE_DIR, 'staticfiles')

# STATIC_ROOT = os.path.join(BASE_DIR,'/')
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )
STATICFILES_DIRS = (
    os.path.join(CORE_DIR, 'static'),
)

MEDIA_URL ='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#social_app custom settings
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]


SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'login'


#SOCIAL_AUTH_FACEBOOK_KEY = "498988634986408"
SOCIAL_AUTH_FACEBOOK_KEY = "685092066525481"
#SOCIAL_AUTH_FACEBOOK_SECRET = "c34ce9ed7316a728579693ef783969b4"
SOCIAL_AUTH_FACEBOOK_SECRET = "98f2bc4cd3ae2d2c9dff9ef28a0f063b"
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "754626614119-gkca93lhnptb6epu2o79gek4rd2nqr8j.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "537291948966-ac8ruql0q0s46aoiruhtec5ooscniq3e.apps.googleusercontent.com"
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"
# add this
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('name', 'name'),
    ('email', 'email'),
    ('picture', 'picture'),
    ('link', 'profile_url'),
]
